title: programming
description: codingWorkSpace
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-seo-tag
- jekyll-paginate
- jekyll-sitemap
- jekyll-gallery-generator
baseurl: /

source: .
destination: ./_site
permalink: /:title